### PR TITLE
Change legacy gdxcc dependency to use gamsapi instead

### PR DESCRIPTION
**Pull request by ptsavol**
This PR does the following:
- Remove gdxcc as dependency
- Add gamsapi>47 as dependency. This removes Python 3.6 & 3.7 support. 
- Modify imports to get gdxcc from gams.core.gdx
- Bump version to 2.2.0
- Update Github actions to newer versions
- Update CHANGELOG

Note:
Could not find a way to install just the core parts of `gamsapi`. Doing `pip install gamsapi[core]` installs `gamsapi`, `numpy` and `ply` packages, where `gamsapi` is exactly the same package as when simply doing `pip install gamsapi`. Doing `pip install gamsapi[core] --no-deps` is the same as `pip install gamsapi`.

Fixes Issue #8

### CODE REVIEW

**Comment by ptsavol** [comment]
@erkkar Did you notice this? What do you think?

**Comment by erkkar** [comment]
Looks good! Maybe remove the ‘This is a fork of...’ from README since after merging it does not make sense anymore. 

Did all tests pass?

**Comment by ptsavol** [comment]
Readme.md has been updated and all the tests pass.

**Comment by erkkar** [comment]
Thank you, @ptsavol!

**Pull request merged**
